### ISSUE TITLE
Issue on page /notebooks/08-01-Identifying-hot-pixels.html

### ISSUE THREAD

**Issue by shafransky93** [astropy/ccd-reduction-and-photometry-guide#330]
Example 6.1.2
FileNotFoundError: [Errno 2] No such file or directory: 'combined_dark_exposure_1000.0.fit.bz2'

**Comment by mwcraig** [comment]
Thanks for reporting this @shafransky93 -- it has been fixed in the development version at http://www.astropy.org/ccd-reduction-and-photometry-guide/v/dev/notebooks/08-01-Identifying-hot-pixels.html and will be fixed in edition 2.0.1, hopefully coming in a day or two.

Also, how would you like to be listed in the acknowledgements? I can use just your GitHub username or your full name.

**Comment by shafransky93** [comment]
To whom it may concern:

Thanks. Full name works.

 Benjamin Shafransky

**Comment by shafransky93** [comment]
Looks like the directory is still missing.

**Comment by mwcraig** [comment]
How are you running the notebooks?

**Comment by mwcraig** [comment]
also, thanks for letting me know!

**Comment by shafransky93** [comment]
Np. This is the site example page that I'm seeing this on. 6.1.2 Example the ran code for this example shows this error.

**Comment by mwcraig** [comment]
Ah, thanks -- I see it now. I'm not sure why this doesn't cause a failure when the book is built but will track it down.

**Comment by mwcraig** [comment]
This time it really does seem to be fixed 😀: http://www.astropy.org/ccd-reduction-and-photometry-guide/v/dev/notebooks/08-01-Identifying-hot-pixels.html
